episerver-graph-api/AlloyDemoKit/Controllers/GraphController.cs
using System.Runtime.Caching;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using EpiServer.AlloyDemo.GraphAPI.Helpers;
using EpiServer.AlloyDemo.GraphAPI.Models.GraphApi;
using EpiServer.AlloyDemo.GraphAPI.Models.Pages;
using EpiServer.AlloyDemo.GraphAPI.Models.ViewModels;
using EPiServer.Web.Mvc;

namespace EpiServer.AlloyDemo.GraphAPI.Controllers
{
    public class GraphController : PageController<GraphApiPage>
    {
        public async Task<ActionResult> Index(GraphApiPage currentPage)
        {
            return View(PageViewModel.Create(currentPage));

            ClaimsPrincipal principal = HttpContext.User as ClaimsPrincipal;
            if (principal.Identity.IsAuthenticated)
            {
                string upn = principal.FindFirst("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn")?.Value;
                if (string.IsNullOrEmpty(upn))
                {
                    upn = principal.FindFirst("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name")?.Value;
                }

                upn = HttpUtility.UrlEncode(upn);

                //var graphService = ServiceLocator.Current.GetInstance<GraphService>();
                var graphProvider = new GraphAuthProvider(MemoryCache.Default);
                var graphService = new GraphService(MemoryCache.Default, new GraphSdkHelper(graphProvider), graphProvider);
                CompositeGraphObject compositeGraphObject = await graphService.GetUserJson(upn, null);

                currentPage.CompositeGraphObject = compositeGraphObject;

                return View(PageViewModel.Create(currentPage));
            }

            return View();
        }

        [ChildActionOnly]
        public ActionResult GetReactHtmlPage()
        {
            return new FilePathResult("~/react/build/index.html", "text/html");
        }
    }
}

episerver-graph-api/AlloyDemoKit/Views/Graph/Index - Copy.cshtml
@using EpiServer.AlloyDemo.GraphAPI
@model IPageViewModel<GraphApiPage>

@{
    ViewBag.Title = "Graph API";
    //Layout = "~/Views/Shared/Layouts/_LeftNavigation.cshtml";
}

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


<div class="row">
    <div class="span4">
        <i class="material-icons">person</i>
        <h2>Personal</h2>
        @{;
            <div>
                <span class="bold">Name: </span>
                <span>@Model.CurrentPage.CompositeGraphObject.User.DisplayName</span>
            </div>

            <div>
                <span class="bold">Mail: </span>
                <span>@Model.CurrentPage.CompositeGraphObject.User.Mail</span>
            </div>

            <div>
                <span class="bold">Job title: </span>
                <span>@Model.CurrentPage.CompositeGraphObject.User.JobTitle</span>
            </div>

            <div>
                <span class="bold">Mobile phone: </span>
                <span>@Model.CurrentPage.CompositeGraphObject.User.MobilePhone</span>
            </div>

            if (Model.CurrentPage.CompositeGraphObject.User.BusinessPhones.Any())
            {
                <span class="bold">Business phone: </span>
                <span>@Model.CurrentPage.CompositeGraphObject.User.BusinessPhones.First()</span>
            }

            <div>
                <span class="bold">Language: </span>
                <span>@Model.CurrentPage.CompositeGraphObject.User.PreferredLanguage</span>
            </div>

            <div>
                <span class="bold">User was created on: </span>
                <span>@Model.CurrentPage.CompositeGraphObject.User.AdditionalData.FirstOrDefault(k => k.Key == "createdDateTime").Value</span>
            </div>
        }
    </div>
    <div class="span4">
        <i class="material-icons">photo_camera</i>
        <h2>Picture</h2>
        @{
            <div>
                <img src="@Model.CurrentPage.CompositeGraphObject.Picture" style="height: 140px;" />
            </div>
        }
    </div>
    <div class="span4">
        <i class="material-icons">business</i>
        <h2>Company</h2>
        @{
            <div>
                <span class="bold">Company: </span>
                <span>@Model.CurrentPage.CompositeGraphObject.User.CompanyName</span>
            </div>

            <div>
                <span class="bold">Country: </span>
                <span>@Model.CurrentPage.CompositeGraphObject.User.Country</span>
            </div>

            <div>
                <span class="bold">Office location: </span>
                <span>@Model.CurrentPage.CompositeGraphObject.User.OfficeLocation</span>
            </div>

            <div>
                <span class="bold">Department: </span>
                <span>@Model.CurrentPage.CompositeGraphObject.User.Department</span>
            </div>
        }
    </div>
</div>
<div class="row">
    <div class="span4">
        <i class="material-icons">email</i>
        <h2>Last email</h2>
        @if(Model.CurrentPage.CompositeGraphObject.Messages != null)
        {
            <div>
                <span class="bold">From: </span>
                <span>@Model.CurrentPage.CompositeGraphObject.Messages[0].From.EmailAddress.Address</span>
            </div>

            <div>
                <span class="bold">Subject: </span>
                <span>@Model.CurrentPage.CompositeGraphObject.Messages[0].Subject</span>
            </div>

            <div>
                <span class="bold">Content: </span>
                <span>@Model.CurrentPage.CompositeGraphObject.Messages[0].BodyPreview</span>
            </div>

            <div>
                <span class="bold">Received: </span>
                <span>@Model.CurrentPage.CompositeGraphObject.Messages[0].ReceivedDateTime</span>
            </div>
        }
    </div>
    <div class="span4">
        <i class="material-icons">calendar_today</i>
        <h2>Upcoming events</h2>
        @if (Model.CurrentPage.CompositeGraphObject.Events != null)
        {
            <div>
                <span class="bold">Subject: </span>
                <span>@Model.CurrentPage.CompositeGraphObject.Events[5].Subject</span>
            </div>

            <div>
                <span class="bold">When: </span>
                <span>@Model.CurrentPage.CompositeGraphObject.Events[5].Start.DateTime</span>
            </div>

            <div>
                @if (Model.CurrentPage.CompositeGraphObject.Events[5].Locations.Any())
                {
                    <span class="bold">Location: </span>
                    <span>@Model.CurrentPage.CompositeGraphObject.Events[5].Locations.First().DisplayName</span>
                }
            </div>

            <div>
                <span class="bold">Content: </span>
                @Html.Raw(Model.CurrentPage.CompositeGraphObject.Events[5].Body.Content)
            </div>
        }
    </div>
    <div class="span4">
        <i class="material-icons">group</i>
        <h2>Contacts:</h2>
        @if (Model.CurrentPage.CompositeGraphObject.Contacts != null)
        {
            foreach (var contact in Model.CurrentPage.CompositeGraphObject.Contacts)
            {
                <div>
                    <span class="bold">@contact.DisplayName: </span>
                    <span>@contact.EmailAddresses.First().Address</span>
                </div>
            }
        }
    </div>
</div>
<div class="row">
    <div class="span4">
        <i class="material-icons">insert_drive_file</i>
        <h2>Sharepoint sites:</h2>
        @if (Model.CurrentPage.CompositeGraphObject.DriveItems != null)
        {
            foreach (var item in Model.CurrentPage.CompositeGraphObject.DriveItems)
            {
                <div>
                    <span class="bold">@item.WebUrl: </span>
                    <a href="@item.WebUrl">link</a>
                </div>
            }
        }
    </div>
    <div class="span4">
        <i class="material-icons">notes</i>
        <h2>OneNote sections:</h2>
        @if (Model.CurrentPage.CompositeGraphObject.OnenoteSections != null)
        {
            foreach (var item in Model.CurrentPage.CompositeGraphObject.OnenoteSections)
            {
                <div>
                    <span class="bold">@item.DisplayName: </span>
                    <a href="@item.Links.OneNoteWebUrl.Href">link</a>
                </div>
            }
        }
    </div>
    <div class="span4">
        <i class="material-icons">event_note</i>
        <h2>Planner tasks:</h2>
        @if (Model.CurrentPage.CompositeGraphObject.PlannerTasks != null)
        {
            foreach (var item in Model.CurrentPage.CompositeGraphObject.PlannerTasks)
            {
                <div>
                    <span class="bold">Plan name: </span>
                    <span>@Model.CurrentPage.CompositeGraphObject.PlannerPlans[0].Title</span>
                </div>

                <div>
                    <span class="bold">Title: </span>
                    <span>@item.Title</span>
                </div>

                <div>
                    <span class="bold">Date: </span>
                    <span>@item.DueDateTime</span>
                </div>
            }
        }
    </div>
</div>

<div id="embedded-feed" style="width:800px;"></div>
<script type="text/javascript" src="https://s0-azure.assets-yammer.com/assets/platform_embed.js"></script>
<script type="text/javascript">
    yam.connect.embedFeed({
        container: "#embedded-feed",
        feedType: 'topic',
        feedId: '12667207680',
        config: {
            promptText: "Comment on this blog post",
            showOpenGraphPreview: false,
            header: false,
            footer: false
        },
        private: false
    });
</script>

<div class="row">
    <div class="span4">
        <i class="material-icons">group_work</i>
        <h2>Joined teams:</h2>
        @if (Model.CurrentPage.CompositeGraphObject.JoinedTeams != null)
        {
            foreach (var item in Model.CurrentPage.CompositeGraphObject.JoinedTeams)
            {
                <div>
                    <span class="bold">Name: </span>
                    <span>@item.DisplayName</span>
                </div>

                <div>
                    <span class="bold">Description: </span>
                    <span>@item.Description</span>
                </div>
            }
        }
    </div>
    <div class="span4">
        <i class="material-icons">group</i>
        <h2>Team members:</h2>
        @if (Model.CurrentPage.CompositeGraphObject.TeamMembers != null)
        {
            foreach (var item in Model.CurrentPage.CompositeGraphObject.TeamMembers)
            {
                <div>
                    <div>
                        <span class="bold">@item.DisplayName: </span>
                        <span>@item.Mail</span>
                    </div>
                </div>
            }
        }
    </div>
    <div class="span4">
        <i class="material-icons">donut_large</i>
        <h2>Team channels:</h2>
        @if (Model.CurrentPage.CompositeGraphObject.TeamChannels != null)
        {
            foreach (var item in Model.CurrentPage.CompositeGraphObject.TeamChannels)
            {
                <div>
                    <span class="bold">Name: </span>
                    <span>@item.DisplayName</span>
                </div>

                <div>
                    <span class="bold">Description: </span>
                    <span>@item.Description</span>
                </div>
            }

            foreach (var item in Model.CurrentPage.CompositeGraphObject.TeamChannelTabs)
            {
                <div>
                    <span class="bold">Channel tab: </span>
                    <span>@item.DisplayName</span>
                </div>
            }
        }
    </div>
</div>
<div class="row">
    <div class="span4">
        <i class="material-icons">apps</i>
        <h2>My applications:</h2>
        @if (Model.CurrentPage.CompositeGraphObject.AppRoleAssignments != null)
        {
            foreach (var item in Model.CurrentPage.CompositeGraphObject.AppRoleAssignments)
            {
                <div>
                    <span class="bold">@item.ResourceDisplayName </span>
                </div>
            }
        }
    </div>
</div>

<div style='max-width: 640px'>
    <div style='position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;'>
        <iframe width="640" height="360" src="https://web.microsoftstream.com/embed/video/d6b091bf-77db-4bb9-9001-9885aa417f4c?autoplay=false&amp;showinfo=true" style="border: none;" allowfullscreen style='position: absolute; top: 0; left: 0; right: 0; bottom: 0; height: 100%; max-width: 100%;'></iframe>
    </div>
</div>




<div style="margin-bottom: 200px"></div>

episerver-graph-api/AlloyDemoKit/Views/Graph/Index.cshtml
@using EpiServer.AlloyDemo.GraphAPI
@using EPiServer.Core
@model IPageViewModel<GraphApiPage>

@{
    ViewBag.Title = "Graph API";
Layout = null;
}

<script>
    window.intranetSettings = {
        blocks: [
            @foreach (var block in Model.CurrentPage.MainContentArea.Items)
            {
                <text>"@block.GetContent().Name",</text>
            }
        ]
    }
</script>


@Html.Action("GetReactHtmlPage", "Graph")